/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankmanagementsystem;
import java.sql.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Mo7amed
 */
public class additional_details extends javax.swing.JFrame {

    /**
     * Creates new form additional_details
     */
    Connection con;
    String name="",phone="",address="",gender="",city="",id="";
    char [] password=new char[5];
    public additional_details() {
        initComponents();
        try{
        con= DriverManager.getConnection("jdbc:mysql://localhost:3306/bankook", "root", "root");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Connection Failed");}
        this.setLocationRelativeTo(null);
    }
    public additional_details(String name,String phone,String address,String gender,String city,String id){
        this.name=name;
        this.phone=phone;
        this.address=address;
        this.gender=gender;
        this.city=city;
        this.id=id;
        /*
        System.out.println(name);
        System.out.println(phone);
        System.out.println(address);
        System.out.println(gender);
        System.out.println(city);
        System.out.println(id);
        */
        initComponents();
        try{
        con= DriverManager.getConnection("jdbc:mysql://localhost:3306/bankook", "root", "root");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Connection Failed");}
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        saving_btn = new javax.swing.JRadioButton();
        cur_btn = new javax.swing.JRadioButton();
        fixed_btn = new javax.swing.JRadioButton();
        pin_txt = new javax.swing.JPasswordField();
        atm_btn = new javax.swing.JCheckBox();
        internet_btn = new javax.swing.JCheckBox();
        mobile_btn = new javax.swing.JCheckBox();
        email_btn = new javax.swing.JCheckBox();
        back_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        AccountType_label = new javax.swing.JLabel();
        PIN_label = new javax.swing.JLabel();
        digit4_label = new javax.swing.JLabel();
        ServiceRequierd_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("createAccounte (cont.)");

        buttonGroup1.add(saving_btn);
        saving_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saving_btn.setSelected(true);
        saving_btn.setText("Saving Account");
        saving_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saving_btnActionPerformed(evt);
            }
        });

        buttonGroup1.add(cur_btn);
        cur_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cur_btn.setText("Current Account");
        cur_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cur_btnActionPerformed(evt);
            }
        });

        buttonGroup1.add(fixed_btn);
        fixed_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fixed_btn.setText("Fixed Deposit Account");
        fixed_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixed_btnActionPerformed(evt);
            }
        });

        buttonGroup2.add(atm_btn);
        atm_btn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        atm_btn.setSelected(true);
        atm_btn.setText("ATM CARD ");

        buttonGroup2.add(internet_btn);
        internet_btn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        internet_btn.setText("Internet Banking");
        internet_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internet_btnActionPerformed(evt);
            }
        });

        buttonGroup2.add(mobile_btn);
        mobile_btn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mobile_btn.setText("Mobile Banking");
        mobile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_btnActionPerformed(evt);
            }
        });

        buttonGroup2.add(email_btn);
        email_btn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        email_btn.setText("Email Alerts");

        back_btn.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        back_btn.setText("Back");
        back_btn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        submit_btn.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        submit_btn.setText("Submit");
        submit_btn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        AccountType_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AccountType_label.setText("Account Type");

        PIN_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PIN_label.setText("PIN");

        digit4_label.setText("(4 digits)");

        ServiceRequierd_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ServiceRequierd_label.setText("Service Requierd:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cur_btn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AccountType_label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saving_btn, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fixed_btn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ServiceRequierd_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(atm_btn)
                                            .addComponent(digit4_label)
                                            .addComponent(PIN_label, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mobile_btn))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(internet_btn)
                                    .addComponent(email_btn))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AccountType_label, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saving_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cur_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fixed_btn)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PIN_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(digit4_label))
                    .addComponent(pin_txt))
                .addGap(62, 62, 62)
                .addComponent(ServiceRequierd_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atm_btn)
                    .addComponent(internet_btn))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile_btn)
                    .addComponent(email_btn))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn)
                    .addComponent(submit_btn))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saving_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saving_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saving_btnActionPerformed

    private void cur_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cur_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cur_btnActionPerformed

    private void fixed_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixed_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fixed_btnActionPerformed

    private void mobile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobile_btnActionPerformed

    private void internet_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internet_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internet_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        new CreateAccounte_page().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        
       try {
           String accType="saving";
        if(cur_btn.isSelected())accType="current";
        else if(fixed_btn.isSelected())accType="fixed";
        
        String service="ATM";
        if(mobile_btn.isSelected())service="mobile";
        else if(internet_btn.isSelected())service="internet";
        else if(email_btn.isSelected())service="email";
        password =pin_txt.getPassword();
        String s="";
        for(int i=0;i<password.length;i++){
            s+=password[i];
        }
        int pass_=Integer.parseInt(s);
        
            PreparedStatement stmt1;
           stmt1 = con.prepareStatement("insert into client (name,phone,address,gender,city,National_ID,PIN,acc_type,service) values(?,?,?,?,?,?,?,?,?)");
            stmt1.setString(1, name);
            stmt1.setString(2, phone);
            stmt1.setString(3, address);
            stmt1.setString(4, gender);
            stmt1.setString(5, city);
            stmt1.setString(6, id);
            stmt1.setInt(7, pass_);
            stmt1.setString(8, accType);
            stmt1.setString(9, service);
            stmt1.executeUpdate();
            //=====
            PreparedStatement stmt2;
            stmt2 = con.prepareStatement("insert into info (name2, id, balance,account_type,PIN) values(?,?,?,?,?)");
            stmt2.setString(1, name);
            stmt2.setString(2, id);
            stmt2.setInt(3, 0);
            stmt2.setString(4, accType);
            stmt2.setInt(5, pass_);
            stmt2.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"successful add");
            new CreateAccounte_page().setVisible(true);
            this.dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"unsuccessful add");
            }
        
    }//GEN-LAST:event_submit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(additional_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(additional_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(additional_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(additional_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new additional_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountType_label;
    private javax.swing.JLabel PIN_label;
    private javax.swing.JLabel ServiceRequierd_label;
    private javax.swing.JCheckBox atm_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton cur_btn;
    private javax.swing.JLabel digit4_label;
    private javax.swing.JCheckBox email_btn;
    private javax.swing.JRadioButton fixed_btn;
    private javax.swing.JCheckBox internet_btn;
    private javax.swing.JCheckBox mobile_btn;
    private javax.swing.JPasswordField pin_txt;
    private javax.swing.JRadioButton saving_btn;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
